### ISSUE TITLE
pull request template

### ISSUE THREAD

**Issue by jonschlinkert** [generate/generate-contributing#3]
I'd love some editorial review/feedback on the contents of this "microlib" pull request template I created:
https://gist.github.com/jonschlinkert/08d8c000b5cf59ac7042762fc1e36453. 

For a while now I've wanted to create a pr template that can be used as a starting point in our microlibs, generators, plugins, etc. I'd like for it to be friendly and welcoming to newcomers, hopefully that comes across.  Admittedly I didn't spend too long on it, but I was hoping for feedback before getting too detailed. anyway, this is a start.

@dawsonbotsford, @doowb, @pointnet?

**Comment by doowb** [comment]
@jonschlinkert I see a couple of typos, and there is no "other" checklist, but otherwise it looks really good.

### Typos
- Under [fixing typos](https://gist.github.com/jonschlinkert/08d8c000b5cf59ac7042762fc1e36453#fixing-typos) need to add `info` to `Add your to the contributors array in package.json!`
- Under [readme advice](https://gist.github.com/jonschlinkert/08d8c000b5cf59ac7042762fc1e36453#readme-advice), `Any changes made .verb.md` should be `Any changes made to .verb.md`
- Under [package.json contributors example](https://gist.github.com/jonschlinkert/08d8c000b5cf59ac7042762fc1e36453#packagejson-contributors) our full names are flipped.

**Comment by jonschlinkert** [comment]
lol our full names. I was really paying attention to detail on this one lol

**Comment by jonschlinkert** [comment]
closing, the templates have completely changed
